name: anydrawer
description: Unleash flexibility in your Flutter app with our package. Display a drawer anywhere, no scaffold needed. Try it now!
version: 1.0.6
homepage: https://github.com/oi-narendra/anydrawer

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#

screenshots:
  - description: "Example in mobile"
    path: screenshots/scnsht1.png
  - description: "Examples in Web"
    path: screenshots/scnsht2.png
